apiVersion: apps/v1
kind: Deployment
metadata:
  name: workorder-api
  namespace: workorder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workorder-api
  template:
    metadata:
      labels:
        app: workorder-api
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/auth-path: "auth/kubernetes"
        vault.hashicorp.com/role: "workorder-api"
        vault.hashicorp.com/agent-inject-secret-db-secrets.properties: "homelab/data/workorder-api"
        vault.hashicorp.com/agent-inject-template-db-secrets.properties: |
          {{- with secret "homelab/data/workorder-api" -}}
          quarkus.datasource.username={{ .Data.data.db_username }}
          quarkus.datasource.password={{ .Data.data.db_password }}
          {{- end -}}
    spec:
      serviceAccountName: workorder-api-sa
      containers:
        - name: workorder-api
          image: ivancl4udio/workorder-quarkus-pg-rest-api:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: QUARKUS_CONFIG_LOCATIONS
              value: "/vault/secrets/db-secrets.properties"
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: workorder-api-config
                  key: HTTP_PORT
            - name: DB_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: workorder-api-config
                  key: DB_JDBC_URL
            - name: CUSTOMER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: workorder-api-config
                  key: CUSTOMER_BASE_URL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: workorder-api-svc
  namespace: workorder-api
spec:
  selector:
    app: workorder-api
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
