apiVersion: v1
kind: ConfigMap
metadata:
  name: workorder-api-config
  namespace: workorder-api
data:
  HTTP_PORT: "8080"
  DB_JDBC_URL: "jdbc:postgresql://postgres.db.svc.cluster.local:5432/workorder_db"
  CUSTOMER_BASE_URL: "http://customer-api-svc.customer-api.svc.cluster.local:80"
